import Header from './header'
import Review from './review'
import CardSection from './cardSection'
import Reply from './reply'

const STRESSTXT = 'So gooood IASA SDFO OAJSDJKF KSADF IRIRIF IAO AAAAH HAHAHAHAHA HAAAAAAHH HTAOVJDSA SDJKFSJK KJSAFJ JKSAJKFD SALDFKJ SJADNKF ASFRJKNDSJK NKJSANF KSAJF KSADDJ FKASRJNGDF KVASNDF KSAJDN FKARJENDFKJ NSAKDF KAK AKSDJF NJ ASDF NSJDF JSDNF NJNKJAS FJKASJKDFKJKJ AKSDJKFJ KKAKSDK FJSDJKFK AJSD SKKDFKJ ASKDJFKSADJ FKASKDKJ FJKSAKF JJJKASDFJ JJ JFJ FJSKKAKDKFJFJ JFFJ JSAJKKFK K FK     KK  K KK K K K KK K   K K ASJDJF J J J SJJASA DSFOF RJASJD FKS IS IAISD FN ASDJFJJ AKSKDIRJJFJAKSDKDFI FIIR FJAKSDJFJF IRJFA KKSJDDJ FNAJNSJDFJ JFRJ JAJS DJDSFJ KAKKSDFJ JJSJDAK KKSKDFJJ J JFDAJJSADKJ JJAJSDFK KJSAJJF JJFK KASUEJRNF VMAXFNEKWJDSNA KFJNSA UCKJNER DSKJAFNASDKJ NFKJASDN JSAJKDFJKA SJKFAWENIKJ SDNFKJNSD NSAJDKFNJ NJSANFJD NSAJNF JAN SOO GOOD! AAAAAHHHHHHH OOHHHH NOOOO ASDHHHHH AAAAHHHAHAHAHA So gooood IASA SDFO OAJSDJKF KSADF IRIRIF IAO AAAAH HAHAHAHAHA HAAAAAAHH HTAOVJDSA SDJKFSJK KJSAFJ JKSAJKFD SALDFKJ SJADNKF ASFRJKNDSJK NKJSANF KSAJF KSADDJ FKASRJNGDF KVASNDF KSAJDN FKARJENDFKJ NSAKDF KAK AKSDJF NJ ASDF NSJDF JSDNF NJNKJAS FJKASJKDFKJKJ AKSDJKFJ KKAKSDK FJSDJKFK AJSD SKKDFKJ ASKDJFKSADJ FKASKDKJ FJKSAKF JJJKASDFJ JJ JFJ FJSKKAKDKFJFJ JFFJ JSAJKKFK K FK     KK  K KK K K K KK K   K K ASJDJF J J J SJJASA DSFOF RJASJD FKS IS IAISD FN ASDJFJJ AKSKDIRJJFJAKSDKDFI FIIR FJAKSDJFJF IRJFA KKSJDDJ FNAJNSJDFJ JFRJ JAJS DJDSFJ KAKKSDFJ JJSJDAK KKSKDFJJ J JFDAJJSADKJ JJAJSDFK KJSAJJF JJFK KASUEJRNF VMAXFNEKWJDSNA KFJNSA UCKJNER DSKJAFNASDKJ NFKJASDN JSAJKDFJKA SJKFAWENIKJ SDNFKJNSD NSAJDKFNJ NJSANFJD NSAJNF JAN SOO GOOD! So gooood IASA SDFO OAJSDJKF KSADF IRIRIF IAO AAAAH HAHAHAHAHA HAAAAAAHH HTAOVJDSA SDJKFSJK KJSAFJ JKSAJKFD SALDFKJ SJADNKF ASFRJKNDSJK NKJSANF KSAJF KSADDJ FKASRJNGDF KVASNDF KSAJDN FKARJENDFKJ NSAKDF KAK AKSDJF NJ ASDF NSJDF JSDNF NJNKJAS FJKASJKDFKJKJ AKSDJKFJ KKAKSDK FJSDJKFK AJSD SKKDFKJ ASKDJFKSADJ FKASKDKJ FJKSAKF JJJKASDFJ JJ JFJ FJSKKAKDKFJFJ JFFJ JSAJKKFK K FK     KK  K KK K K K KK K   K K ASJDJF J J J SJJASA DSFOF RJASJD FKS IS IAISD FN ASDJFJJ AKSKDIRJJFJAKSDKDFI FIIR FJAKSDJFJF IRJFA KKSJDDJ FNAJNSJDFJ JFRJ JAJS DJDSFJ KAKKSDFJ JJSJDAK KKSKDFJJ J JFDAJJSADKJ JJAJSDFK KJSAJJF JJFK KASUEJRNF VMAXFNEKWJDSNA KFJNSA UCKJNER DSKJAFNASDKJ NFKJASDN JSAJKDFJKA SJKFAWENIKJ SDNFKJNSD NSAJDKFNJ NJSANFJD NSAJNF JAN SOO GOOD!'

const App = () => {
  return (
    <div className='container'>
      <Header title='Reviews' />

      <CardSection />

      <div className='review-container'>
        <Review
          title="Taco John's"
          stars='5'
          text={STRESSTXT}
          author='john Doe'
          date='01/01/2019'
        />
        <Reply
          text={STRESSTXT}
          author='Jane Doe'
          date='01/01/2019'
        />
      </div>

    </div>
  )
}

export default App
