
const STRESSTXT = 'ufdsj hbkjhKA aaAAAhdhh hhajsdfjhh jjashdfhj jashdf jhhh h hhA a SHDHJ ajk iajkfsdhhjK asdfjkjkjksf gooood IASA SDFO OAJSDJKF KSADF IRIRIF IAO AAAAH HAHAHAHAHA HAAAAAAHH HTAOVJDSA SDJKFSJK KJSAFJ JKSAJKFD SALDFKJ SJADNKF ASFRJKNDSJK NKJSANF KSAJF KSADDJ FKASRJNGDF KVASNDF KSAJDN FKARJENDFKJ NSAKDF KAK AKSDJF NJ ASDF NSJDF JSDNF NJNKJAS FJKASJKDFKJKJ AKSDJKFJ KKAKSDK FJSDJKFK AJSD SKKDFKJ ASKDJFKSADJ FKASKDKJ FJKSAKF JJJKASDFJ JJ JFJ FJSKKAKDKFJFJ JFFJ JSAJKKFK K FK     KK  K KK K K K KK K   K K ASJDJF J J J SJJASA DSFOF RJASJD FKS IS IAISD FN ASDJFJJ AKSKDIRJJFJAKSDKDFI FIIR FJAKSDJFJF IRJFA KKSJDDJ FNAJNSJDFJ JFmndsfan RJ JAJS DJDSFJ KAKKSDFJ JJSJDAK KKSKDFJJ J JFDAJJSADKJ JJAJSDFK KJSAJJF JJFK KASUEJRNF VMAXFNEKWJDSNA KFJNSA UCKJNER DSKJAFNASDKJ NFKJASDN JSAJKDFJKA SJKFAWENIKJ SDNFKJNSD NSAJDKFNJ NJSANFJD NSAJNF JAN SOO GOOD! AAAAAHHHHHHH OOHHHH NOOOO ASDHHHHH AAAAHHHAHAHAHA So gooood IASA SDFO OAJSDJKF KSADF IRIRIF IAO AAAAH HAHAHAHAHA HAAAAAAHH HTAOVJDSA SDJKFSJK KJSAFJ JKSAJKFD SALDFKJ SJADNKF ASFRJKNDSJK NKJSANF KSAJF KSADDJ FKASRJNGDF KVASNDF KSAJDN FKARJENDFKJ NSAKDF KAK AKSDJF NJ Aasdfjk jasdfjk jkasdkf ur asdf SDF NSJDF JSDNF NJNKJAS FJKASJKDFKJKJ AKSDJKFJ KKAKSDK FJSDJKFK AJSD SKKDFKJ ASKDJFKSADJ FKASKDKJ FJKSAKF JJJKASDFJ JJ JFJ FJSKKAKDKFJFJ JFFJ JSAJKKFK K FK     KK  K KK K K K KK K   K K ASJDJF J J J SJJASA DSFOF RJASJD FKS IS IAISD FN ASDJFJJ AKSKDIRJJFJAKSDKDFI FIIR FJAKSDJFJF IRJFA KKSJDDJ FNAJNSJDFJ JFRJ JAJS DJDSFJ KAKKSDFJ JJSJDAK KKSKDFJJ J JFDAJJSADKJ JJAJSDFK KJSAJJF JJFK KASUEJRNF VMAXFNEKWJDSNA KFJNSA UCKJNER DSKJAFNASDKJ NFKJASDN JSAJKDFJKA SJKFAWENIKJ SDNFKJNSD NSAJDKFNJ NJSANFJD NSAJNF JAN SOO GOOD! So gooood IASA SDFO OAJSDJKF KSADF IRIRIF IAO AAAAH HAHAHAHAHA HAAAAAAHH HTAOVJDSA SDJKFSJK KJSAFJ JKSAJKFD SALDFKJ SJADNKF ASFRJKNDSJK NKJSANF KSAJF KSADDJ FKASRJNGDF KVASNDF KSAJDN FKARJENDFKJ NSAKDF KAK AKSDJF NJ ASDF NSJDF JSDNF NJNKJAS FJKASJKDFKJKJ AKSDJKFJ KKAKSDK FJSDJKFK AJSD SKKDFKJ ASKDJFKSADJ FKASKDKJ FJKSAKF JJJKASDFJ JJ JFJ FJSKKAKDKFJFJ JFFJ JSAJKKFK K FK     KK  K KK K K K KK K   K K ASJDJF J J J SJJASA DSFOF RJASJD FKS IS IAISD FN ASDJFJJ AKSKDIRJJFJAKSDKDFI FIIR FJAKSDJFJF IRJFA KKSJDDJ FNAJNSJDFJ JFRJ JAJS DJDSFJ KAKKSDFJ JJSJDAK KKSKDFJJ J JFDAJJSADKJ JJAJSDFK KJSAJJF JJFK KASUEJRNF VMAXFNEKWJDSNA KFJNSA UCKJNER DSKJAFNASDKJ NFKJjasfjd jkkjasdf i8w8oru asASD JOAJOWR ASDF ASDN JSAJKDFJKA SJKFAWENIKJ SDNFKJNSD NSAJDKFNJ NJSANFJD NSAJNF JAN SOO GOOD!'

const formatDate = str => {
  const zeros = n => {
    const str = n.toString()
    if (str.length === 1) return `0${str}`
    return str
  }
  const date = new Date(str)
  return `${zeros(date.getMonth() + 1)}/${zeros(date.getDate())}/${zeros(date.getFullYear())}`
}

const truncate = (str, limit = 100) => str.slice(0, limit)

export { truncate, formatDate, STRESSTXT }
